<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManagedDrive.HelperProtocol\ManagedDrive.HelperProtocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ManagedDrive.Tests" />
  </ItemGroup>

</Project>
