<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="winfsp.net" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ManagedDrive.Tests" />
  </ItemGroup>

</Project>
